services:
  postgres_authentication:
    image: postgres:17.1-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication_db
    ports:
      - "5432:5432"
